# ============================================================================
# aidc Homebrew formula -- SOURCE OF TRUTH / BOOTSTRAP COPY.
#
# The canonical, always-current formula is GENERATED by
# .github/workflows/release.yml from release/Formula/aidc.rb.tmpl on every
# tagged release, and committed to the SEPARATE tap repo pacepace/homebrew-aidc
# (a Homebrew tap MUST live in a repo named homebrew-<name>; it cannot live
# here). This checked-in copy exists so the formula is reviewable in-repo and so
# the tap can be bootstrapped by hand before the release automation is wired up.
#
# !! sha256 below is a PLACEHOLDER (all zeros). It is NOT installable as-is. !!
# The real value is the sha256 of the published source tarball
#   https://github.com/pacepace/aidc/archive/refs/tags/vX.Y.Z.tar.gz
# which the release workflow computes and substitutes automatically. To publish
# by hand, see Formula/README.md.
#
# This is RUBY that runs unprivileged on every user's machine via `brew install`
# (and `brew test`). Any execution construct beyond the documented allowlist is
# rejected by release/lint-formula-template.sh.
# ============================================================================
class Aidc < Formula
  desc "AI Dev Container: sandboxed Claude Code, locked-down egress, taint detection"
  homepage "https://github.com/pacepace/aidc"
  url "https://github.com/pacepace/aidc/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on "jq"
  depends_on "gettext" # provides envsubst

  def install
    # Install everything from the tarball EXCEPT tests/ (host smoke harness only;
    # not needed at runtime and would bloat the install). .devcontainer/ is
    # load-bearing (dev-base build context) but Dir["*"] omits dotfiles, so it is
    # listed explicitly.
    libexec.install Dir["*", ".devcontainer"].reject { |f| f == "tests" }
    bin.install_symlink libexec/"scripts/aidc"
  end

  def caveats
    <<~EOS
      aidc requires Docker with the `docker compose` v2 plugin (bundled with Docker
      Desktop; on Linux install `docker-compose-plugin` alongside the engine).
      Install Docker from https://www.docker.com/products/docker-desktop/ (macOS)
      or your distro's package manager (Linux), and ensure the daemon is running:

        docker info

      First `aidc create` builds the dev container images locally (~10-15 min on a
      fresh install). Subsequent creates reuse the built images and complete in ~30s.

      After a `brew upgrade aidc`, the next `aidc create` will rebuild container
      images against the new Dockerfile (~10-15 min). Already-running sessions keep
      their old image until you `aidc kill` them. Old aidc image tags remain on disk
      until you remove them with docker (typically a few GB per prior version);
      cleanup is opt-in so you can keep them for rollback.

      To pin to a specific major.minor line (e.g. for compliance review):

        brew install aidc@1.0
        brew link --overwrite --force aidc@1.0
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/aidc help").lines.first
  end
end
